# AndroidComplianceConfig.yml

compliancePolicy:
  Name: "Android Compliance Policy"
  Platform: "android"
  Description: "Enforces compliance on Android devices"
  SettingCount: 10
  MarkAsSupervised: false
  SettingPrecedence: true

complianceSettings:
  - SettingName: "Minimum OS Version"
    DataType: "String"
    Operator: "GreaterThan"
    Value: "9.0"

  - SettingName: "Maximum Failed Login Attempts"
    DataType: "Integer"
    Operator: "LessThan"
    Value: 5

  - SettingName: "Require Password"
    DataType: "Boolean"
    Operator: "Equals"
    Value: true

  - SettingName: "Password Expiration Days"
    DataType: "Integer"
    Operator: "GreaterThan"
    Value: 0

  - SettingName: "Password Minimum Length"
    DataType: "Integer"
    Operator: "GreaterThan"
    Value: 8

  - SettingName: "Require Encryption"
    DataType: "Boolean"
    Operator: "Equals"
    Value: true

  - SettingName: "Device Threat Level"
    DataType: "String"
    Operator: "Equals"
    Value: "Low"

  - SettingName: "Device Health Attestation State"
    DataType: "String"
    Operator: "Equals"
    Value: "Healthy"

  - SettingName: "Require Approved System Apps"
    DataType: "Boolean"
    Operator: "Equals"
    Value: true

  - SettingName: "Minimum Security Patch Level"
    DataType: "String"
    Operator: "GreaterThan"
    Value: "2021-01-01"

assignment:
  Name: "Android Compliance Assignment"
  Platform: "android"
