name: Apply Compliance Policies

on:
  push:
    branches:
      - main

jobs:
  deploy_compliance:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: microsoft/setup-powershell@v1
        with:
          pwsh-version: '7.x'  # Replace with the desired PowerShell version

      - name: Determine Changed Files
        id: determine_changes
        run: |
          $changes = git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          echo "::set-output name=changes::$changes"

      - name: Execute PowerShell Script - Apply Android Compliance
        if: contains(steps.determine_changes.outputs.changes, 'DeviceCompliance\AndroidComplianceConfig.yml')
        run: |
          .\ApplyCompliancePolicies.ps1 -ComplianceConfig "DeviceCompliance\AndroidComplianceConfig.yml"

      - name: Execute PowerShell Script - Apply iOS Compliance
        if: contains(steps.determine_changes.outputs.changes, 'DeviceCompliance\IOSComplianceConfig.yml')
        run: |
          .\ApplyCompliancePolicies.ps1 -ComplianceConfig "DeviceCompliance\IOSComplianceConfig.yml"

      - name: Execute PowerShell Script - Apply macOS Compliance
        if: contains(steps.determine_changes.outputs.changes, 'DeviceCompliance\MacOSComplianceConfig.yml')
        run: |
          .\ApplyCompliancePolicies.ps1 -ComplianceConfig "DeviceCompliance\MacOSComplianceConfig.yml"

      - name: Execute PowerShell Script - Apply Windows Compliance
        if: contains(steps.determine_changes.outputs.changes, 'DeviceCompliance\WindowsComplianceConfig.yml')
        run: |
          .\ApplyCompliancePolicies.ps1 -ComplianceConfig "DeviceCompliance\WindowsComplianceConfig.yml"
