name: Apply Compliance Policies

on:
  push:
    branches:
      - main

jobs:
  deploy_compliance:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: microsoft/setup-powershell@v1

      - name: Determine Changed Files
        id: determine_changes
        run: |
          $changes = git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          echo "::set-output name=changes::$changes"

      - name: Execute PowerShell Script - Apply Android Compliance
        if: contains(steps.determine_changes.outputs.changes, 'AndroidComplianceConfig.yml')
        run: |
          .\ApplyCompliancePolicies.ps1 -ComplianceConfig "AndroidComplianceConfig.yml"

      - name: Execute PowerShell Script - Apply IOS Compliance
        if: contains(steps.determine_changes.outputs.changes, 'IOSComplianceConfig.yml')
        run: |
          .\ApplyCompliancePolicies.ps1 -ComplianceConfig "IOSomplianceConfig.yml"

      - name: Execute PowerShell Script - Apply Android Compliance
        if: contains(steps.determine_changes.outputs.changes, 'MacOSComplianceConfig.yml')
        run: |
          .\ApplyCompliancePolicies.ps1 -ComplianceConfig "MacOSComplianceConfig.yml"

      - name: Execute PowerShell Script - Apply Android Compliance
        if: contains(steps.determine_changes.outputs.changes, 'WindowsComplianceConfig.yml')
        run: |
          .\ApplyCompliancePolicies.ps1 -ComplianceConfig "WindowsComplianceConfig.yml"

  # Add additional jobs for other compliance policies or configurations if needed
