name: Apply Enrollment Policies

on:
  push:
    branches:
      - main

jobs:
  deploy_compliance:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: microsoft/setup-powershell@v1
        with:
          pwsh-version: '7.x'  # Replace with the desired PowerShell version

      - name: Determine Changed Files
        id: determine_changes
        run: |
          $changes = git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          echo "::set-output name=changes::$changes"

      - name: Execute PowerShell Script - Apply Android Enrollment
        if: contains(steps.determine_changes.outputs.changes, 'Enrollment\AndroidEnrollment.json')
        run: |
          .\ApplyEnrollmentProfiles.ps1 -ComplianceConfig "Enrollment\AndroidEnrollment.json"

      - name: Execute PowerShell Script - Apply IOS Enrollment
        if: contains(steps.determine_changes.outputs.changes, 'Enrollment\IOSEnrollment.json')
        run: |
          .\ApplyEnrollmentProfiles.ps1 -ComplianceConfig "Enrollment\IOSEnrollment.json"

      - name: Execute PowerShell Script - Apply MacOS Enrollment
        if: contains(steps.determine_changes.outputs.changes, 'Enrollment\MacOSEnrollment.json')
        run: |
          .\ApplyEnrollmentProfiles.ps1 -ComplianceConfig "Enrollment\MacOSEnrollment.json"

      - name: Execute PowerShell Script - Apply Windows Autopilot Enrollment
        if: contains(steps.determine_changes.outputs.changes, 'Enrollment\StandardAutopilot.json')
        run: |
          .\ApplyEnrollmentProfiles.ps1 -ComplianceConfig "Enrollment\StandardAutopilot.json"

