name: Apply Enrollment policy

on:
  push:
    branches:
      - main

jobs:
  deploy_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: microsoft/setup-powershell@v1

      - name: Determine Changed Files
        id: determine_changes
        run: |
          $changes = git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          echo "::set-output name=changes::$changes"

      - name: Execute PowerShell Script - Windows Autopilot Configuration
        if: contains(steps.determine_changes.outputs.changes, 'Enrollment\StandardAutopilot.yml')
        run: |
          .\ApplyAutopilotConfig.ps1 -configPath "Enrollment\StandardAutopilot.yml"
